### ISSUE TITLE
wrong location of anterior segments in basal and mid slices?

### ISSUE THREAD

**Issue by AlbertoImg** [bioimaginggroup/cmr#1]
Hi CMR teams,
Is it possible that anterior segments in basal and middle slices are wrongly located?
In AHA segments, anterior segments in basal and middle slices are represented with the numbers 1, and 7, located in the top superior part. 
However, in the bullseye plot in cmr package, the anterior segments are deployed in the top right.
Here you can see a vector x <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16) plotted with bullseye:
![image](https://github.com/bioimaginggroup/cmr/assets/66919617/df98c912-fa63-4ce3-ad23-f2ec0640a92d)

e.g., segment 1 (basal anterior) should be at the top. 

thanks in advance
Best
Alberto

**Comment by volkerschmid** [comment]
Hi Alberto,
Ines, you are right. Seems like we never used the "official" numbering. We have changed the bullseye plot accordingly in the GitHub version and are preparing a cran submission in the next few days.
Best
Volker
